apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qqpi80gsp-go 
  janus-idp.io/tekton: qqpi80gsp-go
  backstage.io/kubernetes-id: qqpi80gsp-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qqpi80gsp-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  