apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qqpi80gsp-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qqpi80gsp-go 
  name: qqpi80gsp-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qqpi80gsp-go 
